Always apply whole config dict
kaufland-ecommerce/esque pull request #135
Opened 2020-01-18 17:30 UTC by Bibob7

Fetch all config attributes of topic and alter it with changed attributes. Then apply whole config to ensure that only changed attributes in config file will be changed.

2020-02-03 08:05 UTC, ognjen-j commented on esque/controller/topic_controller.py
> +    def _get_altered_config(self, topic) -> Dict[str, str]:
Could you add a simple test for this change?

2020-02-05 07:02 UTC, swenzel requested changes

2020-02-05 07:02 UTC, swenzel commented on tests/integration/test_topic_controller.py
> +    initial_topic = Topic(topic_id, config={"cleanup.policy": "delete", "min.compaction.lag": "1000000"})
```suggestion
    initial_topic = Topic(topic_id, config={"cleanup.policy": "delete", "min.compaction.lag.ms": "1000000"})
```

2020-02-05 07:02 UTC, swenzel commented on tests/integration/test_topic_controller.py
> +    assert final_config.get("min.compaction.lag") == "1000000"
```suggestion
    assert final_config.get("min.compaction.lag.ms") == "1000000"
```

2020-02-05 07:02 UTC, swenzel commented on tests/integration/test_topic_controller.py
> +    assert config.get("min.compaction.lag") == "1000000"
```suggestion
    assert config.get("min.compaction.lag.ms") == "1000000"
```

2020-02-05 08:42 UTC, swenzel approved these changes

2020-02-05 08:43 UTC, merged