Consumergroup tests and refactoring
kaufland-ecommerce/esque pull request #53
Opened 2019-09-18 13:33 UTC by MrTrustworthy

2019-09-18 13:36 UTC, MrTrustworthy commented
I need some input regarding the output of `esque describe consumergroup x`. I was thinking about having a "simple summary" description per default, and only providing `-o yaml` etc outputs in case you want to get the full info. Not sure if that's a good idea, but in the spirit of "Kafka Ops for humans" I didn't want to just dump out _all_ info per default.

Short summary currently looks like this:

![image](https://user-images.githubusercontent.com/7623325/65153434-09d5d100-da2a-11e9-89cd-320c4173ab45.png)

2019-09-18 14:00 UTC, hfjn commented
@MrTrustworthy I love to make the describe commands more approachable. But we should agree on a level of verbosity that is consistent for all our commands.

2019-09-18 14:05 UTC, MrTrustworthy commented
@hfjn exactly why I posted that here :D 

Consider the screenshot as my proposal for a level of verbosity for `describe`. Higher verbosity is provided when you specify `-o yaml`, which will give you _all_ details.

2019-09-18 14:14 UTC, hfjn commented
@MrTrustworthy I feel like it doesn't need to be as "speaking" as in your example. I think that might be a pain to maintain for all commands.

2019-09-19 07:45 UTC, MrTrustworthy commented
Proposal:
```
ConsumerGroup pia-mabaya-unit
        active members: 0
        topics: ['shop-product_export_unit'] 
        partitions: 17
        offsets:
               min: 894
               avg: 1908.7
               max: 4052
               total: 32436
        total lag: 90920
```

2019-09-19 08:48 UTC, swenzel commented
I'm not sure if `min/max/avg` over `offsets` is a useful metric. You'll have to know the watermarks of the corresponding topics for those metrics to be meaningful. I'd propose to use the current relative position in percent between low and high watermark. I.e `((offset-low_water)/(high_water-low_water))*100`. This way you can immediately see where the consumer is within the topic. You can then calculate the min/max/avg over those percentages.
Apart from that I also like the less verbose yaml like output :+1:

2019-09-19 08:55 UTC, MrTrustworthy commented
I really like that idea! Not sure how to call that property yet, but something like `Consumergroup Progress: 99.7%` seems like a good, compact piece of information. 

Still, a relative measure will have to be interpreted differently depending on the total size of the topic. 98% on a topic with 100 messages isn't cause for worry, but on a topic with 100 billion entries over multiple years, it represents a considerable amount of lag. So I'd say we have to pair at least one absolute metric in addition to the `progress`. Either `total lag` or `topic size` (aka `sum(high_watermarks)`) would be a good choice, or both.

2019-09-19 08:59 UTC, swenzel commented
Agreed. I'd also keep the lag. Maybe do `min/max/avg` on that, too. Then you can see if it's only for a few partitions or for all of them.

2019-09-19 09:04 UTC, MrTrustworthy commented
Allright, I'll play around a bit and try to find a combination that makes the most sense when viewed by a user. 

One note about the progress calculation `(offset-low_water)/(high_water-low_water))*100`: I'm not sure how I feel about the inclusion of `low_water` in the calculation. On one hand, it gives a more precise piece of info because progress is always based on `alive messages` in the topic. On the other hand, everytime the topic gets retented/compacted, it will cause your progress to move back, which is kinda counter intuitive.

2019-09-19 09:33 UTC, swenzel commented
The same is true if messages come in faster than you can consume or if you stop consuming for a while. It's a stream after all, the progress is dynamic, no way to change that.
Not including the `low_watermark` will lead to very misleading results on very busy topics with retention. Consider `low_watermark = 100k` and `high_watermark=101k`.

Maybe progress is the wrong description then... how about `relative_offset_location`?

2019-09-23 14:32 UTC, Bibob7 commented on esque/cli/output.py
> +def pretty_consumergroup_simple_overview(group: ConsumerGroup) -> str:
ConsumerGroup is missing in the imports

2019-09-23 16:29 UTC, swenzel requested changes
Looks good, waiting for an update to the `pretty_consumergroup_simple_overview`, then everything is fine :+1:

2019-09-27 07:15 UTC, hfjn commented
Added new output formatting and color-coded output. Anyone up for a review? @MrTrustworthy @swenzel @garrettthomaskth 
![image](https://user-images.githubusercontent.com/2960924/65749852-48911880-e107-11e9-85cc-805be6df06cf.png)

2019-09-27 07:16 UTC, hfjn commented
Ah that screenshot has a faked 100.00% lag to show of the color. :P

2019-09-27 13:15 UTC, ognjen-j approved these changes

2020-02-15 10:05 UTC, hfjn commented
I will close this for now since there haven’t been any updates in months. 🙂

2020-02-15 10:05 UTC, closed without merging