62 accept and output standardized stdin and stdout
kaufland-ecommerce/esque pull request #81
Opened 2019-09-30 13:44 UTC by garrettthomaskth

2019-10-14 07:20 UTC, swenzel requested changes

2019-10-14 07:20 UTC, swenzel commented on esque/cli/commands.py
> +    if not sys.__stdin__.isatty():
```suggestion
    if not click.get_text_stream("stdin").isatty():
```

2019-10-14 07:20 UTC, swenzel commented on esque/cli/output.py
> +def format_output(output, output_format):
```suggestion
def format_output(output: Any, output_format: str) -> str:
```

2019-10-14 07:20 UTC, swenzel commented on esque/resources/broker.py
> +    def describe(self) -> dict:
```suggestion
    def describe(self) -> Dict:
```

2019-10-14 07:20 UTC, swenzel commented on esque/cli/commands.py
> +def describe_topic(state, topic_name, output_format):
```suggestion
def describe_topic(state: State, topic_name: str, output_format: str):
```

2019-10-14 07:20 UTC, swenzel commented on esque/cli/commands.py
> +def describe_broker(state, broker_id, output_format):
```suggestion
def describe_broker(state: State, broker_id: str, output_format: str):
```

2019-10-14 07:20 UTC, swenzel commented on esque/cli/commands.py
> +def describe_consumergroup(state, consumer_id, all_partitions, output_format):
```suggestion
def describe_consumergroup(state: State, consumer_id: str, all_partitions: bool, output_format: str):
```

2019-10-14 07:20 UTC, swenzel commented on esque/cli/commands.py
> +def get_topics(state, prefix):
```suggestion
def get_topics(state: State, prefix: str):
```

2019-10-14 07:20 UTC, swenzel commented on tests/conftest.py
> +def interactive_cli_runner(test_config, monkeypatch):
```suggestion
def interactive_cli_runner(test_config: Config, monkeypatch: MonkeyPatch):
```

2019-10-14 07:20 UTC, swenzel commented on tests/conftest.py
> +def non_interactive_cli_runner(test_config, monkeypatch):
```suggestion
def non_interactive_cli_runner(test_config: Config, monkeypatch: MonkeyPatch):
```

2019-10-14 07:20 UTC, swenzel commented on tests/conftest.py
> +def check_and_load_yaml(output: str) -> dict:
```suggestion
def check_and_load_yaml(output: str) -> Dict:
```

2019-10-14 07:20 UTC, swenzel commented on tests/integration/commands/test_creation.py
> +    assert "ERROR: Missing argument TOPIC_NAME" in result.output
Better to use `--verbose` and check for Exception type. If you check for the exact string, the test is too specific.
There are a few more places that I commented with 'exception type'.

2019-10-14 07:20 UTC, swenzel commented on tests/integration/commands/test_creation.py
> +    assert (
exception type

2019-10-14 07:20 UTC, swenzel commented on tests/integration/commands/test_deletion.py
> +    assert "ERROR: Missing argument TOPIC_NAME" in result.output
exception type

2019-10-14 07:20 UTC, swenzel commented on tests/integration/commands/test_deletion.py
> +    assert (
exception type

2019-10-14 07:20 UTC, swenzel commented on tests/integration/commands/test_describe.py
> +    assert "ERROR: Missing argument TOPIC_NAME" in result.output
exception type

2019-10-14 07:20 UTC, swenzel commented on tests/integration/commands/test_describe.py
> +    assert "ERROR: Missing argument BROKER_ID" in result.output
exception type

2019-10-14 07:20 UTC, swenzel commented on tests/integration/commands/test_edit.py
> +    assert 'Error: Missing argument "TOPIC_NAME"' in result.output
exception type

2019-10-14 07:20 UTC, swenzel commented on tests/integration/commands/test_get.py
> +    assert "No config provided in" not in result.output
checking for `result.exit_code == 0` should be sufficient. If anything, you should make sure that no exception whatsoever was thrown by `assert result.exception is None`.

2019-10-14 07:20 UTC, swenzel commented on tests/integration/commands/test_get.py
> +        topic_controller.create_topics([Topic(new_topic, replication_factor=1)])
You could create all at once with:
```python
topic_controller.create_topics([Topic(new_topic, replication_factor=1) for new_topic in new_topics])
```

2019-10-14 07:20 UTC, swenzel commented on tests/integration/commands/test_get.py
> +    retrieved_topics = result.output.split("\n")
You can use your own new feature here. Output it as json and parse it to get the exact list of topics.

2019-10-14 07:20 UTC, swenzel commented on tests/integration/commands/test_get.py
> +    assert "No config provided in" not in result.output
See previous comment about this.

2019-10-14 07:20 UTC, swenzel commented on tests/integration/commands/test_get.py
> +    assert "No config provided in" not in result.output
See previous comment about this.

2019-10-14 07:20 UTC, swenzel commented on tests/integration/commands/test_ping.py
> +    assert "No config provided in" not in result.output
See previous comment about this.

2019-10-14 07:58 UTC, garrettthomaskth commented on esque/cli/commands.py
> +def get_topics(state, prefix):
👍

2019-10-14 08:57 UTC, garrettthomaskth commented on tests/integration/commands/test_get.py
> +        topic_controller.create_topics([Topic(new_topic, replication_factor=1)])
:

2019-10-14 08:57 UTC, garrettthomaskth commented on tests/integration/commands/test_get.py
> +        topic_controller.create_topics([Topic(new_topic, replication_factor=1)])
👍

2019-10-16 14:01 UTC, swenzel commented on esque/cli/helpers.py
> +        raise NoConfirmationPossibleException
Please instantiate your objects!

2019-10-16 14:01 UTC, swenzel commented on esque/cli/output.py
> +    "Topic": green_bold,
I think you need `"topic"` here

2019-10-16 14:01 UTC, swenzel commented on tests/conftest.py
> +from _pytest.monkeypatch import MonkeyPatch
I think you don't need this anymore

2019-10-16 14:01 UTC, swenzel commented on tests/integration/commands/test_get.py
> +        if retrieved_topic:
Now that you're getting a proper list, there won't be empty lines and therefore no empty topics. You can get rid of that check.

2019-10-16 14:01 UTC, swenzel commented on tests/integration/commands/test_get.py
> +def test_smoke_test_get_brokers(non_interactive_cli_runner: CliRunner):
No `loader` here?

2019-10-16 14:01 UTC, swenzel commented on tests/integration/commands/test_ping.py
> +def test_smoke_test_ping(non_interactive_cli_runner: CliRunner):
No `loader` here either?

2019-10-17 16:10 UTC, swenzel approved these changes

2019-10-17 16:10 UTC, swenzel commented on tests/integration/commands/test_get.py
> +        assert retrieved_topic[: len(prefix_1)] == prefix_1
```suggestion
        assert retrieved_topic.startswith(prefix_1)
```

2019-10-21 12:57 UTC, merged